"""Revised

Revision ID: 8a30d2037e11
Revises: b7c6f11b0940
Create Date: 2025-05-21 18:50:36.203295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a30d2037e11'
down_revision: Union[str, None] = 'b7c6f11b0940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('borrowed_books_book_id_fkey', 'borrowed_books', type_='foreignkey')
    op.drop_constraint('borrowed_books_reader_id_fkey', 'borrowed_books', type_='foreignkey')
    op.create_foreign_key(None, 'borrowed_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'borrowed_books', 'readers', ['reader_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.create_foreign_key('borrowed_books_reader_id_fkey', 'borrowed_books', 'readers', ['reader_id'], ['id'])
    op.create_foreign_key('borrowed_books_book_id_fkey', 'borrowed_books', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
